name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: yarn test
